name: Build and Deploy FLOW Antora Documentation

on:
  repository_dispatch:
    types: [build-antora]
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Antora
        run: npm install -g @antora/cli @antora/site-generator

      - name: Install Kroki and Lunr extensions
        run: npm install @antora/lunr-extension asciidoctor-kroki

      - name: Build Documentation
        run: npx antora antora-playbook.yml

      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/site

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
