name: Build and Deploy FLOW Antora Documentation

on:
  repository_dispatch:
    types: [build-antora]
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Antora
        run: npm install -g @antora/cli @antora/site-generator

      - name: Install Kroki and Lunr extensions
        run: npm install @antora/lunr-extension asciidoctor-kroki

      - name: Build Documentation
        run: npx antora antora-playbook.yml

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/site

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
          
